### ISSUE TITLE
Bug: ImportError: cannot import name 'SQLAlchemyBaseUserTableUUID' from 'fastapi_users.db'

### ISSUE THREAD

**Issue by david-shiko** [fastapi-users/fastapi-users#1077]
The bug in short: 
```
from fastapi_users.db import SQLAlchemyBaseUserTableUUID
ImportError: cannot import name 'SQLAlchemyBaseUserTableUUID' from 'fastapi_users.db'
```

This code is also placed here: 
https://github.com/fastapi-users/fastapi-users/blob/3e44abdbeffbe529120f96a91e1f4499202bbe2f/examples/sqlalchemy/app/db.py#L4

And here:
https://fastapi-users.github.io/fastapi-users/10.1/configuration/full-example/#sqlalchemy

Most likely similar to https://github.com/fastapi-users/fastapi-users/issues/1071#issue-1360728701

Environment:
```
david@david-ThinkPad-T14s-Gen-2i:~$ python3 -V
Python 3.10.4
david@david-ThinkPad-T14s-Gen-2i:~$ pip -V
pip 22.2.2 from /home/david/.local/lib/python3.10/site-packages/pip (python 3.10)
david@david-ThinkPad-T14s-Gen-2i:~$ python3 -m venv /home/david/test_venv
david@david-ThinkPad-T14s-Gen-2i:~$ source test_venv/bin/activate
(test_venv) david@david-ThinkPad-T14s-Gen-2i:~$ pip install fastapi-users
Collecting fastapi-users
# ... Installation process here (success)
(test_venv) david@david-ThinkPad-T14s-Gen-2i:~$ python3 -V  # Version inside venv
Python 3.10.4
(test_venv) david@david-ThinkPad-T14s-Gen-2i:~$ pip -V  # Version inside venv
pip 22.0.2 from /home/david/test_venv/lib/python3.10/site-packages/pip (python 3.10)
david@david-ThinkPad-T14s-Gen-2i:~$ uname -a
Linux david-ThinkPad-T14s-Gen-2i 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
david@david-ThinkPad-T14s-Gen-2i:~$ pip show fastapi-users
Name: fastapi-users
Version: 10.1.5
Summary: Ready-to-use and customizable users management for FastAPI
Home-page: 
Author: 
Author-email: François Voron <fvoron@gmail.com>
License: 
Location: /home/david/.local/lib/python3.10/site-packages
Requires: email-validator, fastapi, makefun, passlib, pyjwt, python-multipart
Required-by:
```

The bug:
```
(test_venv) david@david-ThinkPad-T14s-Gen-2i:~$ python3
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fastapi_users.db import SQLAlchemyBaseUserTableUUID
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'SQLAlchemyBaseUserTableUUID' from 'fastapi_users.db' (/home/david/test_venv/lib/python3.10/site-packages/fastapi_users/db/__init__.py)
>>> import fastapi_users.db
>>> fastapi_users.db.SQLAlchemyBaseUserTableUUID
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'fastapi_users.db' has no attribute 'SQLAlchemyBaseUserTableUUID'
```

**Comment by frankie567** [comment]
You need to install the optional dependency for SQAlchemy:

```sh
pip install 'fastapi-users[sqlalchemy]'
```

https://fastapi-users.github.io/fastapi-users/10.1/installation/#with-sqlalchemy-support

**Comment by Xevion** [comment]
So I just ran into this issue last night. Suddenly stopped working.  I have the `sqlalchemy` extra defined properly in my pipenv. Deleted my virtual environment, re-installed from my Pipfile.... No dice.

What ended up working was using `fastapi_users_db_sqlalchemy` instead of `fastapi_users.db`. Also, my issue was not with `SQLAlchemyBaseUserTableUUID` but instead with `SQLAlchemyUserDatabase`.

**Comment by Xevion** [comment]
@frankie567 I apologize, it appears the issue has vanished since I "fixed" it yesterday. I really wish I could demonstrate and help help debug the error is no longer presenting itself. The above import statement resolves in a pipenv-activated `python` shell. When I went through my codebase and reverted `fastapi_users_db_sqlalchemy` into `fastapi_users.db`, no errors were reported, even after restarting my server.

- I have not rebuilt (i.e. deleted and recreated) my virtual environment (pipenv).
- I have reinstalled from/sync'd my Pipfile since then.
- I have restarted Pycharm Professional, my IDE of choice, and the application that starts Uvicorn and runs my FastAPI dev server locally.

Additionally, it appears that I had *two* usages of `fastapi_users_db_sqlalchemy` in my codebase, one which was `SQLAlchemyUserDatabase` as named above, but also `SQLAlchemyBaseUserTable`. I wish I could track down even a semblance of a reason why my error appeared.

**Comment by frankie567** [comment]
No problem! Sometimes, Python virtual environments behave weirdly 🙃

**Comment by david-shiko** [comment]
> You need to install the optional dependency for SQAlchemy:
> 
> ```shell
> pip install 'fastapi-users[sqlalchemy]'
> ```
> 
> https://fastapi-users.github.io/fastapi-users/10.1/installation/#with-sqlalchemy-support

BTW IMHO it's better to create a special error if no the required additional extension was installed to eliminate errors of such 
kind.

**Comment by jissagn** [comment]
There was probably a cycle in the imports. I refactored a bit and the problem is gone.

**Comment by jacksbox** [comment]
Reopening as I ran into the same issue, but have a bit more context:
This error occurs only, if you anywhere else in your code import from `fastapi_users_db_sqlalchemy`, then `from fastapi_users.db import SQLAlchemyUserDatabase` breaks.

**Comment by NickNaskida** [comment]
> Reopening as I ran into the same issue, but have a bit more context:
> This error occurs only, if you anywhere else in your code import from `fastapi_users_db_sqlalchemy`, then `from fastapi_users.db import SQLAlchemyUserDatabase` breaks.

Have you fixed it? Same issue -_-

**Comment by NickNaskida** [comment]
For those who are using alembic for migrations:

This error occurs in migration version file due to import statement.

Here is a fix:

Generate revision and then add import to version file.

This tutorial explains it:

https://harrisonmorgan.dev/2021/02/15/getting-started-with-fastapi-users-and-alembic/

**Comment by Bongomannn** [comment]
pip install fastapi_users_db_sqlalchemy does work for me maybe an installation error occured at some time. I had also messed something up before.

**Comment by sobameshi0901** [comment]
In my case, I encountered a circular import issue with these imports:
```python
from fastapi_users.db import SQLAlchemyUserDatabase
from fastapi_users_db_sqlalchemy.access_token import SQLAlchemyAccessTokenDatabase
```

This resulted in the error:
```
from fastapi_users.db import SQLAlchemyUserDatabase 
E   ImportError: cannot import name 'SQLAlchemyUserDatabase' from 'fastapi_users.db'
```

I resolved the issue by importing both from fastapi_users_db_sqlalchemy:
```python
from fastapi_users_db_sqlalchemy import SQLAlchemyUserDatabase
from fastapi_users_db_sqlalchemy.access_token import SQLAlchemyAccessTokenDatabase
```

**Comment by rioachuzia** [comment]
I also ran into the exact same issue with:

```python
from fastapi_users.db import BeanieUserDatabase
```

because elsewhere in my code I used

```python
from fastapi_users_db_beanie import BeanieUserDatabase
```

Making sure I use either one or the other consistently was the solution for me.

**Comment by 7adidaz** [comment]
I faced the same problem and as @ rioachuzia mentioned its either `fastapi_users.db`  or `fastapi_users_db_sqlalchemy` using both at the same times breaks it.
