### ISSUE TITLE
Problem in getting current_user

### ISSUE THREAD

**Issue by LidorPrototype** [fastapi-users/fastapi-users#1281]
## Describe the bug

When trying to get current user I'm getting the error 
```python
File ".\main.py", line 788, in tester
    current_user = Depends(FastAPIUsers.current_user())
AttributeError: type object 'FastAPIUsers' has no attribute 'current_user'
```
The code is:
```python
from fastapi_users import FastAPIUsers
current_user = Depends(FastAPIUsers.current_user())
```

## Expected behavior

I expected to get the current user that sent the request to my FastAPI in any format that is readable

## Configuration
 - Python version : 3.8.2
 - FastAPI version : 0.103.0
 - FastAPI Users version : 12.1.2

## Additional context

I built the API with FastAPI and I'm trying to find out which is the user that sent the request to me

**Comment by nurettn** [comment]
@LidorPrototype hi,

In the [documentation](https://fastapi-users.github.io/fastapi-users/12.1/usage/current-user/) it's saying:

> FastAPI Users provides a dependency callable to easily inject authenticated user in your routes. They are available from your FastAPIUsers instance.

So you need to instantiate a FastAPIUsers object and derive current_users from this. Like this:

```
from fastapi_users import FastAPIUsers
...
fastapi_users = FastAPIUsers[User, PydanticObjectId](get_user_manager, [auth_backend])
current_active_user = fastapi_users.current_user(active=True)
``` 

I believe that the [examples](https://fastapi-users.github.io/fastapi-users/12.1/usage/current-user/) in the documentation are confusing for users because the variable `fastapi_users` has the same name as the package.
